language: go
go:
  - 1.6
  - 1.7
  - tip
script: make build
install:
  - go get github.com/op/go-logging
  - go get github.com/miekg/dns

notifications:
  email:
    recipients:
      - shell909090@gmail.com
    on_success: never
    on_failure: change